# Old test

In [1]:
import os
import pandas as pd

In [2]:
data='mooc'
ss = 'ts_tpr_remove_mss'
upto = 0.7
load_location = '/raid/t2/TGN_adv/poisoned_data'
path = f'{load_location}/{data}/{ss}'

In [3]:
df1 = pd.read_csv(path+f'/modified_{data}_{ss}_sparsified_{upto}.csv')
df1.head()

   Unnamed: 0  src   dst          time  adv  ext_roll
0           0    1  7048      0.000000    0         0
1           1   13  7055  38940.620456    1         0
2           2   15  7056  39332.948185    1         0
3           3   15  7055  39332.948185    1         0
4           4   13  7056  39332.948185    1         0

In [4]:
df1['src'].min(), df1['src'].max(), df1['dst'].min(), df1['dst'].max()

(1, 7047, 7048, 7144)

In [ ]:
# df1[df1['src'] > 7047]  # (1, 8968, 10, 9227)

In [5]:
df2 = pd.read_csv(load_location+f'/{data}/ml_{data}.csv')
df2.head()

   Unnamed: 0  u     i    ts  label  idx
0           0  1  7048   0.0    0.0    1
1           1  1  7049   6.0    0.0    2
2           2  1  7050  41.0    0.0    3
3           3  1  7049  49.0    0.0    4
4           4  1  7050  51.0    0.0    5

In [6]:
df2['u'].min(), df2['u'].max(), df2['i'].min(), df2['i'].max()

(1, 7047, 7048, 7144)

In [ ]:
icml_path = '/raid/t2/TGN_adv/poisoned_data_icml/poisoned_data'
dataset_name = 'wikipedia'
folder_path = icml_path +"/"+ dataset_name
ss = 'ts_tpr_remove_mss'
upto=0.7

# /raid/t2/TGN_adv/poisoned_data_icml/poisoned_data/wikipedia/ts_tpr_remove_mss
# print(folder_path+f'/{ss}/modified_{dataset_name}_{ss}_sparsified_{upto}.csv')

df1 = pd.read_csv(folder_path+f'/{ss}/modified_{dataset_name}_{ss}_sparsified_{upto}.csv')
df1.head()

df1['src'].min(), df1['src'].max(), df1['dst'].min(), df1['dst'].max()

In [ ]:
# df1[df1['adv'] == 1]
df1['int_roll'].unique(), df2['int_roll'].unique()

In [ ]:
import pickle
import numpy as np

with open(pkl_file_path, 'rb') as file:
    data = pickle.load(file)

for key in data.keys():
    print(f'length of {key}: {len(data[key])}')

In [ ]:

# Path to the .npz file
filename = 'ext_full.npz'
npz_file_path = os.path.join(path, filename)

# Load the .npz file
data = np.load(npz_file_path)

# Check the keys (the variable names inside the .npz file)
print("Keys in the .npz file:", data.keys())

# Access data using the keys
for key in data:
    print(f"{key}: {len(data[key])}")

# Always remember to close the file when done (this is a good practice)
data.close()

In [ ]:

# Path to the .npz file
filename = 'ext_full.npz'
npz_file_path = os.path.join(path2, filename)

# Load the .npz file
data = np.load(npz_file_path)

# Check the keys (the variable names inside the .npz file)
print("Keys in the .npz file:", data.keys())

# Access data using the keys
for key in data:
    print(f"{key}: {len(data[key])}")

# Always remember to close the file when done (this is a good practice)
data.close()

In [ ]:
import pickle
import numpy as np
import os

# File paths
path = '/raid/t2/TGN_adv/tspear/DATA/wiki_tspear'
filename = 'ext_full.pkl'
pkl_file_path = os.path.join(path, filename)
npz_file_path = os.path.join(path, 'ext_full.npz')

# Load the pickle file
with open(pkl_file_path, 'rb') as file:
    data = pickle.load(file)

# Ensure the directory exists before saving the npz file
# os.makedirs(os.path.dirname(npz_file_path), exist_ok=True)

# Save the data as npz file
# Assuming data is a dictionary-like structure with arrays/lists as values
np.savez(npz_file_path, **data)

print(f"Data saved to {npz_file_path}")

In [ ]:
# indptr=ext_full_indptr, indices=ext_full_indices, ts=ext_full_ts, eid=ext_full_eid

ext_full_indptr = data['indptr']
ext_full_indices = data['indices']
ext_full_ts = data['ts']
ext_full_eid = data['eid']

In [ ]:
# Save each element individually if the data contains elements of varying shapes
save_path = '/raid/t2/TGN_adv/tspear/DATA/{}/ext_full.npz'.format('wiki_tspear')
print(save_path)

# Loop through the elements in the dictionary and save them individually
# np.savez(save_path, **data)
# np.savez(save_path, data=np.array(data, dtype=object))

In [ ]:
# np.savez('/raid/t2/TGN_adv/tspear/DATA/{}/ext_full.npz'.format('wiki_tspear'),
#          **data
#          )

np.savez(save_path, indptr=ext_full_indptr, indices=ext_full_indices, ts=ext_full_ts, eid=ext_full_eid)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/raid/t2/TGN_adv/tspear/DATA/{}/edges.csv'.format('wiki_tspear'))
df.head()

In [ ]:
_df = pd.read_csv('/raid/t2/TGN_adv/tspear/DATA/{}/edges.csv'.format('wiki'))
_df.head()

In [ ]:
df['adv'].unique()

In [ ]:
new_df = df.drop(columns=['Unnamed: 0', 'adv'], axis=1)
new_df.head()

In [ ]:
new_df.to_csv('/raid/t2/TGN_adv/tspear/DATA/{}/edges.csv'.format('wiki_tspear'))

# New tests

In [ ]:
import os
import torch
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [ ]:
tgl_path = '/raid/t2/TGN_adv/tspear/DATA/UCI'
tgl_filename = 'edges.csv'
tgl_feats = 'edge_features.pt'

tgl_filepath = os.path.join(tgl_path, tgl_filename)
# tgl_feats_filepath = os.path.join(tgl_path, tgl_feats)

# edge_feats = torch.load(tgl_feats_filepath)
tgl_df = pd.read_csv(tgl_filepath)
tgl_df.drop(columns=['Unnamed: 0'], axis=1, inplace=True)
tgl_df.head()

In [ ]:
edge_feats.shape, len(tgl_df)

In [ ]:
dataset_name = 'reddit'
dgl_path = f'/raid/t2/TGN_adv/poisoned_data/{dataset_name}'
ss_name = 'ts_tpr_remove_mss'
upto=0.7

# dgl_filename = f'ml_{dataset_name}.csv'
dgl_filename = f'modified_{dataset_name}_{ss_name}_sparsified_{upto}.csv'
dgl_feats = f'ml_{dataset_name}.npy'
dgl_edge_feats = 'edge_features.pt'

dgl_df = pd.read_csv(os.path.join(dgl_path, ss_name, dgl_filename))
dgl_feats = np.load(os.path.join(dgl_path, ss_name, dgl_feats))

dgl_df.drop(columns=['Unnamed: 0'], axis=1, inplace=True)

dgl_df.head()

In [ ]:
new_edge_feats = torch.load(os.path.join(dgl_path, 'ts_tpr_remove_mss', dgl_edge_feats))

In [ ]:
dgl_feats.shape, len(dgl_df), new_edge_feats.shape

In [ ]:
dgl_df['idx'].max()

In [ ]:
# dgl_feats = np.round(dgl_feats, 4)

In [ ]:
# dgl_feats[1]
new_edge_feats[0]

In [ ]:
edge_feats[0]

In [ ]:
# edge_feats[0]
edge_feats[0] == new_edge_feats[0]

In [ ]:
# len(new_edge_feats[1:]), len(edge_feats)