In [1]:
import pandas as pd

import numpy as np

dataset_name = 'wikipedia'
path = rf'/raid/t2/TGN_adv/DyGlib/DG_data/{dataset_name}'
csv_file = f'ml_{dataset_name}.csv'
edge_feat_file= f'ml_{dataset_name}.npy'
node_feat_file= f'ml_{dataset_name}_node.npy'

df = pd.read_csv(f'{path}/{csv_file}')
edge_feat = np.load(f'{path}/{edge_feat_file}', allow_pickle=True)
node_feat = np.load(f'{path}/{node_feat_file}', allow_pickle=True)

print(edge_feat.shape, node_feat.shape, df.shape, len(df['u'].unique())+len(df['i'].unique()) )

df.head()

(157475, 172) (9228, 172) (157474, 6) 9227

   Unnamed: 0  u     i     ts  label  idx
0           0  1  8228    0.0    0.0    1
1           1  2  8229   36.0    0.0    2
2           2  2  8229   77.0    0.0    3
3           3  3  8230  131.0    0.0    4
4           4  2  8229  150.0    0.0    5

In [1]:
import pandas as pd

import numpy as np

dataset_name = 'uci'
path = rf'/raid/t2/TGN_adv/DyGlib/DG_data/{dataset_name}'
csv_file = f'ml_{dataset_name}.csv'
edge_feat_file= f'ml_{dataset_name}.npy'
node_feat_file= f'ml_{dataset_name}_node.npy'

df = pd.read_csv(f'{path}/{csv_file}')
edge_feat = np.load(f'{path}/{edge_feat_file}', allow_pickle=True)
node_feat = np.load(f'{path}/{node_feat_file}', allow_pickle=True)

edge_feat.shape, node_feat.shape, df.shape, len(df['u'].unique())+len(df['i'].unique()) 

df.head()

   Unnamed: 0  u  i      ts  label  idx
0           0  1  2       0      0    1
1           1  3  4  114878      0    2
2           2  5  2  373430      0    3
3           3  6  7  398658      0    4
4           4  8  7  398795      0    5

In [48]:
df['id'] = df['u'].astype(str) +"_"+ df['i'].astype(str)
df['id'] = df['id']

df['reversed_id'] = df['id'].astype(str).apply(lambda x: (x.split('_')[1] + '_' + x.split('_')[0]))

df['reverse_exists'] = df['reversed_id'].isin(df['id'])

df.head()

   Unnamed: 0  u  i      ts  label  idx   id reversed_id  reverse_exists
0           0  1  2       0      0    1  1_2         2_1           False
1           1  3  4  114878      0    2  3_4         4_3           False
2           2  5  2  373430      0    3  5_2         2_5           False
3           3  6  7  398658      0    4  6_7         7_6           False
4           4  8  7  398795      0    5  8_7         7_8           False

In [49]:
df['reverse_exists'].value_counts()

reverse_exists
True     46306
False    13529
Name: count, dtype: int64

In [50]:
df[df['reverse_exists'] == 1]

,Unnamed: 0,u,i,ts,label,idx,id,reversed_id,reverse_exists
39,39,41,42,533250,0,40,41_42,42_41,True
54,54,56,57,557587,0,55,56_57,57_56,True
68,68,41,63,561658,0,69,41_63,63_41,True
82,82,67,32,562553,0,83,67_32,32_67,True
84,84,67,32,562688,0,85,67_32,32_67,True
...,...,...,...,...,...,...,...,...,...
59805,59805,969,342,16729218,0,59806,969_342,342_969,True
59806,59806,969,1416,16729463,0,59807,969_1416,1416_969,True
59821,59821,1416,969,16733294,0,59822,1416_969,969_1416,True
59833,59833,1878,1624,16736150,0,59834,1878_1624,1624_1878,True
59834,59834,1878,1624,16736181,0,59835,1878_1624,1624_1878,True

In [34]:
# df[(df['u'] == 3 ) & (df['i'] == 1)]

In [24]:
df['id'].nunique(), len(df['id'])  # (20257, 59835)

df['id'].unique()

array([      12,       34,       52, ..., 18991847, 18991097,  1899277])

In [8]:
import pandas as pd

import numpy as np

dataset_name = 'uci'
ss_name = 'ts_tpr_remove_mss'
path = rf'/raid/t2/TGN_adv/poisoned_data/{dataset_name}/{ss_name}'
print(path)
# modified_uci_ts_tpr_remove_cosine_sparsified_0.7.csv
csv_file = f'modified_{dataset_name}_{ss_name}_sparsified_0.7.csv'
edge_feat_file= f'ml_{dataset_name}.npy'
node_feat_file= f'ml_{dataset_name}_node.npy'

df = pd.read_csv(f'{path}/{csv_file}')
df.sort_values(by=['time'], inplace=True)

df.head()

/raid/t2/TGN_adv/poisoned_data/uci/ts_tpr_remove_mss

    Unnamed: 0  src  dst           time  adv  ext_roll
0            0    9    7  401101.830958    1         0
1            1    9   13  401101.830958    1         0
2            2   12   14  401101.830958    1         0
3            3   17   12  401265.746795    1         0
19          19   36   59  557972.313239    1         0

In [9]:
df['id'] = df['src'].astype(str) +"_"+ df['dst'].astype(str)
df['id'] = df['id']

df['reversed_id'] = df['id'].astype(str).apply(lambda x: (x.split('_')[1] + '_' + x.split('_')[0]))

df['reverse_exists'] = df['reversed_id'].isin(df['id'])

df.head()

,Unnamed: 0,src,dst,time,adv,ext_roll,id,reversed_id,reverse_exists
0,0,9,7,401101.830958,1,0,9_7,7_9,False
1,1,9,13,401101.830958,1,0,9_13,13_9,False
2,2,12,14,401101.830958,1,0,12_14,14_12,False
3,3,17,12,401265.746795,1,0,17_12,12_17,False
19,19,36,59,557972.313239,1,0,36_59,59_36,False

In [10]:
df['reverse_exists'].value_counts()

reverse_exists
True     33253
False    26546
Name: count, dtype: int64

In [11]:
df[df['reverse_exists'] == 1]['adv'].unique()

array([1, 0])

In [12]:
len(df[(df['reverse_exists'] == 1) & (df['adv'] == 1)])

2332

In [13]:
len(df[(df['reverse_exists'] == 1) & (df['adv'] == 0)])

30921

In [45]:
4759 + 710  #  = 5469

5469

In [11]:
# edge feat dimn are number of edges x number of edge features
# node feat dimn are number of nodes + 1 x number of node features

In [7]:
import pandas as pd

import numpy as np

dataset_name = 'enron'
path = rf'/raid/t2/TGN_adv/DyGlib/DG_data/{dataset_name}'
csv_file = f'ml_{dataset_name}.csv'


df = pd.read_csv(f'{path}/{csv_file}', names=['u', 'i', 'rating', 'ts'], 
                 header=0, skiprows=1)

print(df.shape, len(set(list(df['u'].unique()) + list(df['i'].unique()))))

df.head()

(125234, 4) 22816

         u         i  rating  ts
1 115  170       0.0       0   2
2 115  124  529920.0       0   3
3 115  124  529920.0       0   4
4 115  124  533820.0       0   5
5 115  124  533820.0       0   6

In [8]:
df['u'].max(), df['i'].max(), df['u'].min(), df['i'].min(), max(df['u'].max(), df['i'].max())

(184, 113740399.0, 1, 0.0, 113740399.0)

In [1]:
import os
os.listdir('/raid/t2/TGN_adv/tspear/DATA/UCI/ATTACKED/proposed_TGN_0.3_True_0')

['node_features.pt', 'edge_features.pt', 'ext_full.pkl', 'edges.csv']

In [6]:
df = pd.read_csv('/raid/t2/TGN_adv/tspear/DATA/UCI/ATTACKED/proposed_TGN_0.3_True_0/edges.csv')

print(len(df))
df.head()

72220

   Unnamed: 0  src  dst      time  ext_roll  adv  int_roll
0           0  1.0  2.0       0.0         0    0       NaN
1           1  3.0  4.0  114878.0         0    0       NaN
2           2  5.0  2.0  373430.0         0    0       NaN
3           3  6.0  7.0  398658.0         0    0       NaN
4           4  8.0  7.0  398795.0         0    0       NaN

In [10]:
df[df['adv'] == 0]

       Unnamed: 0     src     dst        time  ext_roll  adv  int_roll
0               0     1.0     2.0         0.0         0    0       NaN
1               1     3.0     4.0    114878.0         0    0       NaN
2               2     5.0     2.0    373430.0         0    0       NaN
3               3     6.0     7.0    398658.0         0    0       NaN
4               4     8.0     7.0    398795.0         0    0       NaN
...           ...     ...     ...         ...       ...  ...       ...
72215       59830  1899.0  1847.0  16735687.0         2    0       NaN
72216       59831  1899.0  1097.0  16735875.0         2    0       NaN
72217       59832  1899.0   277.0  16736042.0         2    0       NaN
72218       59833  1878.0  1624.0  16736150.0         2    0       NaN
72219       59834  1878.0  1624.0  16736181.0         2    0       NaN

[59835 rows x 7 columns]

## Solving UCI

In [1]:
import pandas as pd
import os

dataset_name = 'UCI'
path = rf'/raid/t2/TGN_adv/tspear/DATA/{dataset_name}'

input_file = 'CollegeMsg.txt'
output_file = 'CollegeMsg.csv'

# Assuming the TXT file is tab-delimited
df = pd.read_csv(os.path.join(path, input_file),
                 delimiter=' ', header=None, names=['src', 'dst', 'time'])  # Adjust delimiter if needed

df.head()

   src  dst        time
0    1    2  1082040961
1    3    4  1082155839
2    5    2  1082414391
3    6    7  1082439619
4    8    7  1082439756

In [15]:
print(len(df))

59835

In [ ]:
# Calculate the indices for the splits
total_rows = len(df)
first_split = int(total_rows * 0.7)
second_split = int(total_rows * 0.85)

# Create the 'ext_roll' column
df['ext_roll'] = 0
df.loc[first_split:second_split, 'ext_roll'] = 1
df.loc[second_split:, 'ext_roll'] = 2

# df.to_csv(f'{path}/edges.csv', index=True)

df.head()

   src  dst        time  ext_roll
0    1    2  1082040961         0
1    3    4  1082155839         0
2    5    2  1082414391         0
3    6    7  1082439619         0
4    8    7  1082439756         0

In [41]:
1082155839 - 1082040961 # = 114878
1082414391 - 1082040961

373430

In [2]:
import pandas as pd
import os

dataset_name = 'MOOC'
path = rf'/raid/t2/TGN_adv/tspear/DATA/{dataset_name}'

input_file = 'edges.csv'

# Assuming the TXT file is tab-delimited
df = pd.read_csv(os.path.join(path, input_file),
                #  delimiter=' ', header=None, names=['src', 'dst', 'time']
                 )  # Adjust delimiter if needed

df.head()

   Unnamed: 0  src    dst  time  int_roll  ext_roll
0           0  0.0  980.0   0.0         2         0
1           1  0.0  981.0   6.0         2         0
2           2  0.0  982.0  41.0         1         0
3           3  0.0  981.0  49.0         1         0
4           4  0.0  982.0  51.0         1         0

In [3]:
df['src'].max(), df['dst'].max()

(7046.0, 1076.0, 0.0, 980.0, 7046.0)

In [8]:
# Original string containing strategies
strategies = (
    "ts_tpr_remove_mss "
    "ts_tpr_remove_cosine "
    "ts_tpr_remove_euclidean "
    "ts_tpr_remove_jaccard "
    "ts_tpr_remove_wasserstein "
    "ts_tpr_remove_kl_divergence "
    "ts_tpr_remove_chebyshev "
    "ts_tpr_remove_jensen_shannon_divergence "
    "ts_tpr_remove_TER "
    "ts_tpr_remove_mss_2 "
    "ts_tpr_remove_combined_ter"
)

# Split the string into a list
strategy_list = strategies.split()

# Print the resulting list
print(strategy_list)

['ts_tpr_remove_mss', 'ts_tpr_remove_cosine', 'ts_tpr_remove_euclidean', 'ts_tpr_remove_jaccard', 'ts_tpr_remove_wasserstein', 'ts_tpr_remove_kl_divergence', 'ts_tpr_remove_chebyshev', 'ts_tpr_remove_jensen_shannon_divergence', 'ts_tpr_remove_TER', 'ts_tpr_remove_mss_2', 'ts_tpr_remove_combined_ter']

In [10]:
import pandas as pd
import os

dataset_name = 'bitcoin'
ss_name = 'ts_tpr_remove_cosine'
path = rf'/raid/t2/TGN_adv/poisoned_data/{dataset_name}/{ss_name}'

input_file = f'modified_{dataset_name}_{ss_name}_sparsified_0.7.csv'
print(input_file)

# Assuming the TXT file is tab-delimited
df = pd.read_csv(os.path.join(path, input_file),
                #  delimiter=' ', header=None, names=['src', 'dst', 'time']
                 )  # Adjust delimiter if needed

df['time'] = df['time'].astype(int)

df.head()

modified_bitcoin_ts_tpr_remove_cosine_sparsified_0.7.csv

   Unnamed: 0  src  dst    time  adv  ext_roll
0           0    6    5       0    0         0
1           1    1   15    1199    0         0
2           2   13   16   12313    0         0
3           3   13   10   12359    0         0
4           4    7    5  120759    0         0

In [11]:
dataset_name = 'bitcoin'
for strategy in strategy_list:
    path = rf'/raid/t2/TGN_adv/poisoned_data/{dataset_name}/{strategy}'
    input_file = f'modified_{dataset_name}_{strategy}_sparsified_0.7.csv'
    df = pd.read_csv(os.path.join(path, input_file)) 
    print(strategy, ', '.join(list(df.columns)))

ts_tpr_remove_mss Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_cosine Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_euclidean Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_jaccard Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_wasserstein Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_kl_divergence Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_chebyshev Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_jensen_shannon_divergence Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_TER Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_mss_2 Unnamed: 0, src, dst, time, adv, ext_roll
ts_tpr_remove_combined_ter Unnamed: 0, src, dst, time, adv, ext_roll

In [29]:
import pandas as pd
import os

dataset_name = 'uci'
ss_name = 'ts_tpr_remove_mss'
path = rf'/raid/t2/TGN_adv/sparsified_data/{dataset_name}/{ss_name}'
# path = '/raid/t2/TGN_adv/sparsified_data/uci/ts_tpr_remove_mss'

# input_file = 'uci_ts_tpr_remove_mss_sparsified_0.7.csv' # f'{dataset_name}_{ss_name}_sparsified_0.7.csv'
input_file = f'{dataset_name}_{ss_name}_sparsified_0.7.csv'
print(os.path.join(path, input_file))

# Assuming the TXT file is tab-delimited
df = pd.read_csv(os.path.join(path, input_file),
                #  delimiter=' ', header=None, names=['src', 'dst', 'time']
                 )  # Adjust delimiter if needed

# df['time'] = df['time'].astype(int)

df.head()

/raid/t2/TGN_adv/sparsified_data/uci/ts_tpr_remove_mss/uci_ts_tpr_remove_mss_sparsified_0.7.csv

     u    i       ts  label   idx
0  618    3  1574783      0  7419
1  621  593  1579118      0  7450
2  622  607  1583766      0  7488
3  624  452  1586078      0  7520
4  616  615  1586414      0  7526

In [10]:
len(df[df['adv'] == 1]), len(df[df['adv'] == 0]), len(df[df['adv'] == 1]) + len(df[df['adv'] == 0])

(21078, 38754, 59832)

## Bitcoin

In [2]:
import pandas as pd
import os

dataset_name = 'bitcoin'
path = rf'/raid/t2/TGN_adv/DyGlib/DG_data/{dataset_name}'

input_file = 'soc-sign-bitcoinotc.csv'
# output_file = 'CollegeMsg.csv'

# Assuming the TXT file is tab-delimited
df = pd.read_csv(os.path.join(path, input_file),
                #  delimiter=' ', header=None, names=['src', 'dst', 'time']
                )  # Adjust delimiter if needed

df.columns=['u', 'i', 'label', 'ts']
columns = df.columns.tolist()
columns[-1], columns[-2] = columns[-2], columns[-1]  # Swap the last two columns
df = df[columns]
df['idx'] = df.index
df['label'] = df['label'].astype(float)
df['idx'] = df['idx'].astype(int)
df.sort_values(by=['ts'], inplace=True)

df['ts'] = df['ts'].astype(int)
# df['ts'] = df['ts'] - df['ts'].iloc[0]

df.head()

    u   i          ts  label  idx
0   6   5  1289241941    2.0    0
1   1  15  1289243140    1.0    1
2   4   3  1289245277    7.0    2
3  13  16  1289254254    8.0    3
4  13  10  1289254300    8.0    4

In [46]:
df['ts'].min()

1289241941